name: ifusion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.0
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pip:
    - diffusers==0.21.2
    - einops==0.7.0
    - gdown==5.1.0
    - jaxtyping==0.2.28
    - kornia==0.7.2
    - opencv-python==4.9.0.80
    - pytorch-lightning==2.0.9
    - taming-transformers-rom1504==0.0.6
    - tqdm==4.66.2
    - transformers==4.28.1
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/chinhsuanwu/liegroups.git
